FROM python:3.12-alpine

# Evita a criação de ficheiros .pyc e força o log direto
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instala dependências do Python e o Gunicorn
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . .

# Cria um utilizador não-root e altera o contexto de permissão
RUN adduser -D django-user
USER django-user

EXPOSE 8000

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
